#ifndef PINS_H
#define PINS_H

#ifndef LED_PIN
#define LED_PIN 8
#endif

#ifndef SOIL_MOISTURE_PROBE_1_POWER_PIN
#define SOIL_MOISTURE_PROBE_1_POWER_PIN 21
#endif

#ifndef SOIL_MOISTURE_PROBE_1_AO_PIN
#define SOIL_MOISTURE_PROBE_1_AO_PIN 0
#endif

#ifndef SOIL_MOISTURE_PROBE_2_POWER_PIN
#define SOIL_MOISTURE_PROBE_2_POWER_PIN 20
#endif

#ifndef SOIL_MOISTURE_PROBE_2_AO_PIN
#define SOIL_MOISTURE_PROBE_2_AO_PIN 1
#endif

#ifndef TEMP_SENSOR_TO_92_SDA_PIN
#define TEMP_SENSOR_TO_92_SDA_PIN 6
#endif

#ifndef TEMP_SENSOR_TO_92_SCL_PIN
#define TEMP_SENSOR_TO_92_SCL_PIN 7
#endif

#endif
